# Generated by Django 4.2.4 on 2023-10-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='img',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
